config/routes.rb
Spree::Core::Engine.routes.draw do
  resources :news,
    :controller => "news",
    :only => [:new, :create]
  match 'new-us' => 'news#new', :as => :new_us
  resources :settings,
    :controller => 'settings',
    :only => [:new, :create, :index]
  match 'set-initial' => 'settings#new', :as => :set_initial
  match '/update_tires_select/:iw/:ip/:ii/:ic/:is/:if/:it', :to => 'settings#update_tires_select'
end

app/models/spree/setting.rb
module Spree
  class Setting
    include ActiveModel::Conversion
    include ActiveModel::Validations
    attr_accessor :flag, :ancho, :perfil, :llanta, :velocidad, :ic, :fr, :tttl 
    
    FLAGS_LIST = %w[Spain.png Portugal.png Germany.png Austria.png Belgium.png Nederland.png Luxembourg.png
    Denmark.png Switzerland.png Liechtenstein.png CzechRepublic.png France.png Monaco.png UnitedKingdom.png Italy.png Slovenia.png
    Sweden.png Ireland.png Poland.png Slovakia.png Hungary.png
    Norway.png Finland.png Estonia.png latvia.png Lithuania.png BosniaHerzegovina.png Croatia.png Serbia.png Bulgaria.png Romania.png]
    
    FLAGS_LIST_NEW = {0 => {1 => 'Spain.png', 2 => 'es', 3 => 'es'}, 1 => {1 => 'Portugal.png', 2 => 'pt-PT', 3 => 'pt'}, 2 => {1 => 'Germany.png', 2 => 'de', 3 => 'de'}, 3 => {1 => 'Austria.png', 2 => 'at', 3 => 'at'}, 4 => {1 => 'Belgium.png', 2 => 'nl-BE', 3 => 'be'}, 5 => {1 => 'Nederland.png', 2 => 'nl-NL', 3 => 'nl'}, 6 => {1 => 'Luxembourg.png', 2 => 'lu', 3 => 'lu'}, 7 => {1 => 'Denmark.png', 2 => 'dk', 3 => 'dk'}, 8 => {1 => 'Switzerland.png', 2 => 'ch', 3 => 'ch'}, 9 => {1 => 'Liechtenstein.png', 2 => 'li', 3 => 'li'}, 10 => {1 => 'CzechRepublic.png', 2 => 'cz', 3 => 'cz'}, 11=> {1 => 'France.png', 2 => 'fr', 3 => 'fr'}, 12 => {1 => 'Monaco.png', 2 => 'mc', 3 => 'mc'}, 13 => {1 => 'UnitedKingdom.png', 2 => 'en-GB', 3 => 'gb'}, 14 => {1 => 'Italy.png', 2 => 'it', 3 => 'it'}, 15 => {1 => 'Slovenia.png', 2 => 'si', 3 => 'si'}, 16 => {1 => 'Sweden.png', 2 => 'se', 3 => 'se'}, 17 => {1 => 'Ireland.png', 2 => 'ie', 3 => 'ie'}, 18 => {1 => 'Poland.png', 2 => 'pl', 3 => 'pl'}, 19 => {1 => 'Slovakia.png', 2 => 'sk', 3 => 'sk'}, 20 => {1 => 'Hungary.png', 2 => 'hu', 3 => 'hu'}, 21 => {1 => 'Norway.png', 2 => 'no', 3 => 'no'}, 22 => {1 => 'Finland.png', 2 => 'fi', 3 => 'fi'}, 23 => {1 => 'Estonia.png', 2 => 'ee', 3 => 'ee'}, 24 => {1 => 'latvia.png', 2 => 'lv', 3 => 'lv'}, 25 => {1 => 'Lithuania.png', 2 => 'lt', 3 => 'lt'}, 26 => {1 => 'BosniaHerzegovina.png', 2 => 'ba', 3 => 'ba'}, 27 => {1 => 'Croatia.png', 2 => 'hr', 3 => 'hr'}, 28 => {1 => 'Serbia.png', 2 => 'rs', 3 => 'rs'}, 29 => {1 => 'Bulgaria.png', 2 => 'bg', 3 => 'bg'}, 30 => {1 => 'Romania.png', 2 => 'ro', 3 => 'ro'}}
    
    def persisted?
      false
    end
  
  end
end

app/controllers/spree/settings_controller.rb
class Spree::SettingsController < Spree::BaseController
 
  def new
    @widths = Spree::TireWidth.all
    @profiles = Spree::TireProfile.all
    @innertubes = Spree::TireInnertube.all
    @speeds = Spree::TireSpeedCode.all
    @ics = Spree::TireIc.all
    @frs = Spree::TireFr.all
    @tttls = Spree::TireTttl.all
    render :layout => 'spree/layouts/spree_application'
  end
  
  def index
    prueba = params.select{|k,v| k =~ /.x/}
    session[:locale] = Spree::Setting::FLAGS_LIST_NEW[prueba.keys.first.chop.chop.to_i][3]
    session[:tires] = true
    @searcher = Spree::Config.searcher_class.new(params)
    @products = @searcher.retrieve_products
    render "spree/home/index", :products => @products, :taxon => @taxon
  end
  
  def update_tires_select
    sql = ""
    sql = sql + " and tire_width_id = #{params[:iw]}" unless params[:iw] == "0"
    sql = sql + " and tire_profile_id = #{params[:ip]}" unless params[:ip] == "0"
    sql = sql + " and tire_innertube_id = #{params[:ii]}" unless params[:ii] == "0"
    sql = sql + " and tire_ic_id = #{params[:ic]}" unless params[:ic] == "0"
    sql = sql + " and tire_speed_code_id = #{params[:is]}" unless params[:is] == "0"
    sql = sql + " and tire_fr_id = #{params[:if]}" unless params[:if] == "0"
    sql = sql + " and tire_tttl_id = #{params[:it]}" unless params[:it] == "0"
    tires = Spree::Variant.find_by_sql("SELECT tire_width_id, tire_profile_id, tire_innertube_id, tire_ic_id, tire_speed_code_id, tire_fr_id, tire_tttl_id, is_master
     FROM spree_variants where is_master = 't'" + sql + " group by tire_width_id, tire_profile_id, tire_innertube_id, tire_ic_id, tire_speed_code_id, tire_fr_id, tire_tttl_id, is_master;")
    widths = tires.map {|x| x.tire_width_id}.flatten.uniq
    profiles = tires.map {|x| x.tire_profile_id}.flatten.uniq
    innertubes = tires.map {|x| x.tire_innertube_id}.flatten.uniq
    ics = tires.map {|x| x.tire_ic_id}.flatten.uniq
    speed_codes = tires.map {|x| x.tire_speed_code_id}.flatten.uniq
    frs = tires.map {|x| x.tire_fr_id}.flatten.uniq
    tttls = tires.map {|x| x.tire_tttl_id}.flatten.uniq
    tires = [widths, profiles, innertubes, ics, speed_codes, frs, tttls]
    @width = params[:iw] || 0
    @profile = params[:ip] || 0
    @innertube = params[:ii] || 0
    @ic = params[:ic] || 0
    @speed = params[:is] || 0
    @fr = params[:if] || 0
    @tttl = params[:it] || 0
    if session[:tires].nil?
      render :partial => "tires", :locals => { :tires => tires}
    else
      render :partial => "spree/shared/search_tires", :locals => { :search_tires => tires}
    end
  end
end

app/helpers/spree/settings_helper.rb
module Spree::SettingsHelper
  def submit_flags(id)
    submit t('.submit'), :id => id, :type => :image, :src => "/assets/#{Spree::Setting::FLAGS_LIST[id]}", :height => "30", :width => "40"
  end

end

app/views/spree/settings/_tires.html.erb
<% if tires.blank? -%>
  <p>
    <%= label_tag :Ancho %>
    <%= select_tag :tire_width_id, options_for_select([[t(:width), '']] +
                              @widths.map {|t| [t.name, t.id]},
                            @width ? @width.id : params[:tire_width_id]) %>
    <%= label_tag :Perfil %>
    <%= select_tag :tire_profile_id, options_for_select([[t(:profile), '']] +
                              @profiles.map {|t| [t.name, t.id]},
                            @profile ? @profile.id : params[:tire_profile_id]) %>
    <%= label_tag :Llanta %>
    <%= select_tag :tire_innertube_id, options_for_select([[t(:innertube), '']] +
                              @innertubes.map {|t| [t.name, t.id]},
                            @innertube ? @innertube.id : params[:tire_innertube_id]) %>                        
  </p>
  <p>
    <%= label_tag :IC %>
    <%= select_tag :tire_ic_id, options_for_select([[t(:ic), '']] +
                              @ics.map {|t| [t.name, t.id]},
                            @ic ? @ic.id : params[:tire_ic_id]) %>
    <%= label_tag :Velocidad %>
    <%= select_tag :tire_speed_code_id, options_for_select([[t(:speed_code), '']] +
                              @speeds.map {|t| [t.name, t.id]},
                            @speed ? @speed.id : params[:tire_speed_code_id]) %>
    <%= label_tag :FR %>
    <%= select_tag :tire_fr_id, options_for_select([[t(:fr), '']] +
                              @frs.map {|t| [t.name, t.id]},
                            @fr ? @fr.id : params[:tire_fr_id]) %>
    <%= label_tag :TTTL %>
    <%= select_tag :tire_tttl_id, options_for_select([[t(:tttl), '']] +
                              @tttls.map {|t| [t.name, t.id]},
                            @tttl ? @tttl.id : params[:tire_tttl_id]) %>
  </p>
<% else -%>
  <p>
    <%= label_tag :Ancho %>
    <%= select_tag :tire_width_id, options_for_select([[t(:width), '']] +
                              Spree::TireWidth.find(tires[0]).map {|t| [t.name, t.id]}, @width) %>
    <%= label_tag :Perfil %>
    <%= select_tag :tire_profile_id, options_for_select([[t(:profile), '']] +
                              Spree::TireProfile.find(tires[1]).map {|t| [t.name, t.id]}, @profile) %>
    <%= label_tag :Llanta %>
    <%= select_tag :tire_innertube_id, options_for_select([[t(:innertube), '']] +
                              Spree::TireInnertube.find(tires[2]).map {|t| [t.name, t.id]}, @innertube) %>                        
  </p>
  <p>
    <%= label_tag :IC %>
    <%= select_tag :tire_ic_id, options_for_select([[t(:ic), '']] +
                              Spree::TireIc.find(tires[3]).map {|t| [t.name, t.id]}, @ic) %>
    <%= label_tag :Velocidad %>
    <%= select_tag :tire_speed_code_id, options_for_select([[t(:speed_code), '']] +
                              Spree::TireSpeedCode.find(tires[4]).map {|t| [t.name, t.id]}, @speed) %>
    <%= label_tag :FR %>
    <%= select_tag :tire_fr_id, options_for_select([[t(:fr), '']] +
                              Spree::TireFr.find(tires[5]).map {|t| [t.name, t.id]}, @fr) %>
    <%= label_tag :TTTL %>
    <%= select_tag :tire_tttl_id, options_for_select([[t(:tttl), '']] +
                              Spree::TireTttl.find(tires[6]).map {|t| [t.name, t.id]}, @tttl) %>
  </p>
<% end -%>

app/views/spree/settings/new.html.erb
<h1><%= t('.what_need') %></h1>
<%= form_tag settings_path, :method => :get do -%>
  <div id="tiresSettings">
    <%= render :partial => 'tires' %>
  </div>
  <ul style="display:block;">
    <% for flag in 0..6 -%>
      <li style="display:inline;float:left;"><%= image_submit_tag(Spree::Setting::FLAGS_LIST[flag], :height => "30", :width => "40", :name => flag)  %></li>
    <% end -%>
    <li><h6>Entrega 24 Horas</h6></li>
  </ul>
  <br/>
  <ul>
    <% for flag in 7..15 -%>
      <li style="display:inline;float:left;"><%= image_submit_tag(Spree::Setting::FLAGS_LIST[flag], :height => "30", :width => "40", :name => flag)  %></li>
    <% end -%>
    <li><h6>Entrega 48 Horas</h6></li>
  </ul>
  <br/>
  <ul>
    <% for flag in 16..20 -%>
      <li style="display:inline;float:left;"><%= image_submit_tag(Spree::Setting::FLAGS_LIST[flag], :height => "30", :width => "40", :name => flag)  %></li>
    <% end -%>
    <li><h6>Entrega 2-4 Dias</h6></li>
  </ul>
  <br/>
  <ul>
    <% for flag in 21..30 -%>
      <li style="display:inline;float:left;"><%= image_submit_tag(Spree::Setting::FLAGS_LIST[flag], :height => "30", :width => "40", :name => flag)  %></li>
    <% end -%>
    <li><h6>Entrega 3-4 Dias</h6></li>
  </ul>
<% end -%>